spring:
  application:
    name: snutt-api
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s
  config:
    import: classpath:application-core.yml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  paths-to-match: /v2/**
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
