spring:
  application:
    name: snutt-batch
  main:
    lazy-initialization: true
  http:
    clients:
      connect-timeout: 5s
      read-timeout: 30s
  config:
    import: classpath:application-core.yml
