package com.wafflestudio.snutt.core.common.error

import org.springframework.http.HttpStatus

enum class ErrorType(
    val httpStatus: HttpStatus,
    val errorCode: Long,
    val displayMessage: String,
    val title: String,
) {
    INVALID_PARAMETER(HttpStatus.BAD_REQUEST, 40001, "파라미터 값 오류", "잘못된 요청"),
    INVALID_BODY_FIELD_VALUE(HttpStatus.BAD_REQUEST, 40002, "요청 바디 값 오류", "잘못된 요청"),
    INVALID_REGISTRATION_FOR_PREVIOUS_SEMESTER_COURSE(
        HttpStatus.BAD_REQUEST,
        40005,
        "이전 학기에는 빈자리 알림을 등록할 수 없습니다",
        "알림 등록 불가",
    ),
    INVALID_NICKNAME(HttpStatus.BAD_REQUEST, 40008, "사용할 수 없는 닉네임입니다", "올바르지 않은 닉네임"),
    INVALID_DISPLAY_NAME(HttpStatus.BAD_REQUEST, 40009, "조건에 맞지 않는 이름입니다", "올바르지 않은 이름"),
    TABLE_DELETE_ERROR(HttpStatus.BAD_REQUEST, 40010, "하나 남은 시간표는 삭제할 수 없습니다", "시간표 삭제 불가"),
    INVALID_THEME_COLOR_COUNT(HttpStatus.BAD_REQUEST, 40012, "테마의 색상 개수가 적절하지 않습니다", "올바르지 않은 테마 색상"),
    NOT_DEFAULT_THEME_ERROR(HttpStatus.BAD_REQUEST, 40014, "default 테마가 아닙니다", "기본 테마 아님"),
    TOO_MANY_FILES(HttpStatus.BAD_REQUEST, 40015, "파일 개수가 너무 많습니다", "파일 개수 초과"),
    EMAIL_ALREADY_VERIFIED(HttpStatus.BAD_REQUEST, 40016, "이미 메일 인증이 완료된 유저입니다", "이미 인증된 이메일"),
    TOO_MANY_VERIFICATION_CODE_REQUEST(
        HttpStatus.TOO_MANY_REQUESTS,
        40017,
        "인증 코드는 1분에 1회, 1시간에 최대 5회까지 요청할 수 있습니다",
        "인증 요청 실패",
    ),
    INVALID_VERIFICATION_CODE(HttpStatus.BAD_REQUEST, 40018, "인증 코드가 유효하지 않습니다", "올바르지 않은 인증 코드"),
    ALREADY_LOCAL_ACCOUNT(HttpStatus.BAD_REQUEST, 40019, "이미 로컬 계정이 존재합니다", "로컬 계정 중복"),
    ALREADY_SOCIAL_ACCOUNT(HttpStatus.BAD_REQUEST, 40020, "이미 소셜 계정이 존재합니다", "소셜 계정 중복"),
    NOT_PUBLISHED_THEME(HttpStatus.BAD_REQUEST, 40022, "공유한 테마가 아닙니다", "공유되지 않은 테마"),
    PUBLISHED_THEME_DELETE_ERROR(HttpStatus.BAD_REQUEST, 40023, "테마마켓에서 테마를 내린 뒤 다시 시도해주세요", "테마 삭제 불가"),
    TIMETABLE_LECTURE_REMINDER_INVALID_TIME(HttpStatus.BAD_REQUEST, 40024, "리마인더는 시간이 설정된 강의에만 등록할 수 있어요", "리마인더 등록 불가"),
    DIARY_QUESTION_INVALID(HttpStatus.BAD_REQUEST, 40026, "강의 일기장 질문이 유효하지 않습니다", "올바르지 않은 강의 일기장 질문"),
    DIARY_COMMENT_TOO_LONG(HttpStatus.BAD_REQUEST, 40027, "더 남기고 싶은 말은 최대 1,000자 입력할 수 있습니다", "입력 길이 초과"),
    EVALUATION_CONTENT_BLANK(HttpStatus.BAD_REQUEST, 40028, "강의평 내용을 입력해 주세요", "강의평 내용 없음"),
    EVALUATION_RATING_OUT_OF_RANGE(HttpStatus.BAD_REQUEST, 40029, "평점은 1점부터 5점까지입니다", "올바르지 않은 평점"),
    EVALUATION_REPORT_CONTENT_BLANK(HttpStatus.BAD_REQUEST, 40030, "신고 내용을 입력해 주세요", "신고 내용 없음"),
    INVALID_TIMETABLE_TITLE(HttpStatus.BAD_REQUEST, 40032, "시간표 이름을 입력해 주세요", "올바르지 않은 시간표 이름"),
    INVALID_TIME(HttpStatus.BAD_REQUEST, 40033, "강좌의 시간이 올바르게 설정되었는지 확인해 주시기 바랍니다", "시간대 겹침"),
    INVALID_EVALUATION_SORT(HttpStatus.BAD_REQUEST, 40034, "sort는 latest 또는 recommended 여야 합니다", "잘못된 요청"),
    INVALID_CURSOR(HttpStatus.BAD_REQUEST, 40035, "cursor 형식이 올바르지 않습니다", "잘못된 요청"),
    DIARY_SUBMISSION_TOO_FREQUENT(HttpStatus.BAD_REQUEST, 40036, "오늘 이미 강의 일기장을 작성했습니다", "강의 일기장 작성 불가"),

    SOCIAL_CONNECT_FAIL(HttpStatus.UNAUTHORIZED, 40100, "소셜 로그인에 실패했습니다", "로그인 실패"),
    INVALID_APPLE_LOGIN_TOKEN(HttpStatus.UNAUTHORIZED, 40101, "소셜 로그인에 실패했습니다", "로그인 실패"),
    EXPIRED_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED, 40102, "다시 로그인해 주세요", "로그인 만료"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, 40103, "다시 로그인해 주세요", "로그인 만료"),
    NO_USER_TOKEN(HttpStatus.UNAUTHORIZED, 40104, "앱을 완전히 종료한 뒤, 로그인을 다시 시도해 주시기 바랍니다", "로그인 실패"),

    NOT_MY_EVALUATION(HttpStatus.FORBIDDEN, 40301, "내 강의평이 아닙니다", "권한 없음"),
    WRONG_API_KEY(HttpStatus.FORBIDDEN, 40302, "API 키가 잘못되었습니다", "로그인 실패"),
    WRONG_USER_TOKEN(HttpStatus.UNAUTHORIZED, 40303, "앱을 완전히 종료한 뒤, 로그인을 다시 시도해 주시기 바랍니다", "로그인 실패"),
    USER_NOT_ADMIN(HttpStatus.FORBIDDEN, 40304, "Admin 사용자가 아닙니다. 운영진에게 문의 주시기 바랍니다", "잘못된 요청"),
    WRONG_LOCAL_ID(HttpStatus.FORBIDDEN, 40305, "등록되지 않은 아이디입니다. 다시 입력해 주세요", "로그인 실패"),
    WRONG_PASSWORD(HttpStatus.FORBIDDEN, 40306, "잘못된 비밀번호입니다. 다시 입력해 주세요", "로그인 실패"),
    INVALID_LOCAL_ID(HttpStatus.BAD_REQUEST, 40307, "아이디는 영문 혹은 숫자로 구성된 4~32자여야 합니다", "올바르지 않은 아이디"),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST, 40308, "비밀번호는 영문과 숫자 모두를 포함하는 6~20자여야 합니다", "올바르지 않은 비밀번호"),
    DUPLICATE_LOCAL_ID(HttpStatus.CONFLICT, 40309, "이미 존재하는 아이디입니다", "아이디 등록 실패"),
    DUPLICATE_TIMETABLE_TITLE(HttpStatus.CONFLICT, 40310, "같은 학기에 동일한 이름의 시간표가 있습니다", "시간표 이름 중복"),
    DUPLICATE_LECTURE(HttpStatus.CONFLICT, 40311, "이미 추가된 강좌입니다", "강좌 중복"),
    WRONG_SEMESTER(HttpStatus.FORBIDDEN, 40312, "현재 선택한 학기에서 개설된 강좌가 아닙니다", "학기 불일치"),
    INVALID_TIMETABLE_SEMESTER(HttpStatus.BAD_REQUEST, 40313, "시간표를 생성할 수 없는 학기입니다", "시간표 생성 불가"),
    LECTURE_TIME_OVERLAP(HttpStatus.CONFLICT, 40314, "%s 강의와 시간이 겹칩니다. 강의를 덮어씌우겠습니까?", "시간대 겹침"),
    CANNOT_RESET_CUSTOM_LECTURE(HttpStatus.FORBIDDEN, 40315, "직접 만든 강좌는 초기화할 수 없습니다", "강좌 초기화 불가"),
    INVALID_EMAIL(HttpStatus.BAD_REQUEST, 40316, "이메일 형식이 올바르지 않습니다. 다시 입력해 주세요", "올바르지 않은 이메일"),
    USER_EMAIL_IS_NOT_VERIFIED(HttpStatus.FORBIDDEN, 40317, "이메일 인증이 완료된 후 강의평을 확인할 수 있습니다", "이메일 인증 필요"),

    TIMETABLE_NOT_FOUND(HttpStatus.NOT_FOUND, 40400, "존재하지 않는 시간표입니다", "시간표 없음"),
    PRIMARY_TIMETABLE_NOT_FOUND(HttpStatus.NOT_FOUND, 40401, "대표 시간표가 존재하지 않습니다", "대표 시간표 없음"),
    CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, 40403, "config가 존재하지 않습니다", "설정 없음"),
    FRIEND_NOT_FOUND(HttpStatus.NOT_FOUND, 40404, "친구 관계가 존재하지 않습니다", "친구 관계 없음"),
    USER_NOT_FOUND_BY_NICKNAME(HttpStatus.NOT_FOUND, 40405, "해당 닉네임의 유저를 찾을 수 없습니다", "사용자 없음"),
    THEME_NOT_FOUND(HttpStatus.NOT_FOUND, 40406, "테마를 찾을 수 없습니다", "테마 없음"),
    EV_DATA_NOT_FOUND(HttpStatus.NOT_FOUND, 40407, "강의평 데이터를 찾을 수 없습니다", "강의평 데이터 없음"),
    FRIEND_LINK_NOT_FOUND(HttpStatus.NOT_FOUND, 40409, "친구 링크가 유효하지 않습니다", "올바르지 않은 친구 링크"),
    SOCIAL_PROVIDER_NOT_ATTACHED(HttpStatus.NOT_FOUND, 40410, "소셜 계정이 연동되지 않았습니다", "연동되지 않은 소셜 계정"),
    DIARY_QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, 40411, "강의 일기장 질문이 유효하지 않습니다", "강의 일기장 질문 없음"),
    DIARY_DAILY_CLASS_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, 40412, "강의 일기장 오늘 한 일이 유효하지 않습니다", "강의 일기장 항목 없음"),
    DIARY_TARGET_LECTURE_NOT_FOUND(HttpStatus.NOT_FOUND, 40413, "강의 일기장을 작성할 강의가 없습니다", "강의 일기장 대상 강의 없음"),
    DIARY_SUBMISSION_NOT_FOUND(HttpStatus.NOT_FOUND, 40414, "강의 일기장 기록이 유효하지 않습니다", "강의 일기장 기록 없음"),
    EVALUATION_NOT_FOUND(HttpStatus.NOT_FOUND, 40415, "강의평을 찾을 수 없습니다", "강의평 없음"),
    COURSE_NOT_FOUND(HttpStatus.NOT_FOUND, 40416, "과목을 찾을 수 없습니다", "과목 없음"),
    LECTURE_NOT_FOUND(HttpStatus.NOT_FOUND, 40417, "수강편람에서 찾을 수 없는 강좌입니다", "강좌 없음"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, 40418, "해당 정보로 가입된 사용자가 없습니다", "사용자 없음"),
    TIMETABLE_LECTURE_NOT_FOUND(HttpStatus.NOT_FOUND, 40419, "시간표에 존재하지 않는 강좌입니다", "강좌 없음"),
    COURSEBOOK_NOT_FOUND(HttpStatus.NOT_FOUND, 40420, "수강편람이 아직 등록되지 않았습니다", "수강편람 없음"),

    DUPLICATE_VACANCY_NOTIFICATION(HttpStatus.CONFLICT, 40900, "이미 빈자리 알림을 받고 있는 강좌입니다", "빈자리 알림 중복"),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, 40901, "이미 사용 중인 이메일입니다", "회원가입 실패"),
    DUPLICATE_FRIEND(HttpStatus.CONFLICT, 40902, "이미 친구 관계이거나 친구 요청을 보냈습니다", "친구 요청 중복"),
    INVALID_FRIEND(HttpStatus.CONFLICT, 40903, "친구 요청을 보낼 수 없는 유저입니다", "친구 요청 불가"),
    INVALID_THEME_TYPE(HttpStatus.CONFLICT, 40905, "적절하지 않은 유형의 테마입니다", "올바르지 않은 테마 유형"),
    DUPLICATE_POPUP_KEY(HttpStatus.CONFLICT, 40906, "중복된 팝업 키입니다", "팝업 키 중복"),
    ALREADY_DOWNLOADED_THEME(HttpStatus.CONFLICT, 40907, "이미 다운로드한 테마입니다", "테마 중복"),
    DUPLICATE_SOCIAL_ACCOUNT(HttpStatus.CONFLICT, 40908, "이미 연결된 소셜 계정입니다", "소셜 계정 중복"),
    CANNOT_REMOVE_LAST_AUTH_PROVIDER(HttpStatus.CONFLICT, 40909, "최소 한 개의 로그인 수단은 유지해야 합니다", "로그인 수단 삭제 불가"),
    DUPLICATE_EVALUATION(HttpStatus.CONFLICT, 40910, "이미 강의평을 작성한 강의입니다", "강의평 중복"),
    DUPLICATE_EVALUATION_REPORT(HttpStatus.CONFLICT, 40911, "이미 신고한 강의평입니다", "신고 중복"),
    DUPLICATE_EVALUATION_LIKE(HttpStatus.CONFLICT, 40912, "이미 공감한 강의평입니다", "공감 중복"),
    EVALUATION_LIKE_NOT_FOUND(HttpStatus.CONFLICT, 40913, "공감하지 않은 강의평입니다", "공감 취소 불가"),
    MY_EVALUATION_REPORT(HttpStatus.CONFLICT, 40914, "내 강의평은 신고할 수 없습니다", "강의평 신고 불가"),
    EVALUATION_LECTURE_MISMATCH(HttpStatus.CONFLICT, 40915, "같은 과목의 다른 학기로만 옮길 수 있습니다", "강의평 이동 불가"),
    DUPLICATE_NICKNAME(HttpStatus.CONFLICT, 40916, "사용할 수 없는 닉네임입니다", "닉네임 변경 실패"),

    SOCIAL_PROVIDER_UNAVAILABLE(
        HttpStatus.BAD_GATEWAY,
        50200,
        "소셜 로그인 서버에 문제가 있습니다. 잠시 후 다시 시도해 주세요",
        "소셜 로그인 서버 오류",
    ),
    FEEDBACK_UPSTREAM_UNAVAILABLE(
        HttpStatus.BAD_GATEWAY,
        50201,
        "피드백을 전송하지 못했습니다. 잠시 후 다시 시도해 주세요",
        "피드백 전송 실패",
    ),
}
