spring:
  application:
    name: snutt-migration
  main:
    web-application-type: none
  config:
    import: classpath:application-core.yml

migration:
  mongo:
    database: snutt
  old-ev:
    url: ""
    username: ""
    password: ""

logging:
  level:
    com.wafflestudio.snutt.migration: INFO
